CREATE TABLE evento_auditoria (
    id              NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        VARCHAR2(60)   NOT NULL UNIQUE,
    tramite_id      NUMBER(19)     NOT NULL,
    usuario         VARCHAR2(150)  NOT NULL,
    estado_anterior VARCHAR2(20),
    estado_nuevo    VARCHAR2(20)   NOT NULL,
    event_timestamp TIMESTAMP      NOT NULL
);

CREATE INDEX idx_auditoria_tramite ON evento_auditoria (tramite_id);
CREATE INDEX idx_auditoria_usuario ON evento_auditoria (usuario);
